# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Order')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is done')),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.ToDoList')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
