# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
